name: Deploy to EC2
on: [push]
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 16.171.7.59
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            # Navigate to application directory
            cd /home/ubuntu/algocode-leetcode
            
            # Pull latest changes
            git pull origin main
            
            # Install/update dependencies
            npm ci
            
            # Build the application
            npm run build
            
            # Restart the application (assuming you're using PM2 or similar)
            pm2 restart algocode-leetcode || pm2 start npm --name "algocode-leetcode" -- start
          