name: Deploy to EC2
on: [push]
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
         
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            
            # Create directory if it doesn't exist
            if [ ! -d "algocode" ]; then
              echo "Cloning repository..."
              git clone https://github.com/hxbeeb/AlgoCode.git algocode
            fi
            
            # Navigate to application directory
            cd algocode
            
            # Pull latest changes
            git pull origin main
            
            # Install/update dependencies
            npm install

            # Stop existing PM2 process if running
            pm2 stop algocode 2>/dev/null || true
            pm2 delete algocode 2>/dev/null || true
            
            # Start the application
            pm2 start npm --name "algocode" -- run dev
          